### PR TITLE
fix: Accept argument lists with a -r substring

### LINKED ISSUE #78: Flags parsing fails on specific values '-r' or '-cp'
The flag parser will fail on arguments if the flag string contains '-r' or '--cp'.  This can happen if the following string is past to the executable:

`./some-device-service -confdir config/device-rest-go`

The '-r' in the word 'rest' will cause the parser to fail. 

https://github.com/edgexfoundry/go-mod-bootstrap/blob/e7263182f03795a80ecad393cb2c8c940050476c/bootstrap/flags/flags.go#L80

### PR DESCRIPTION
**Pull request by andresrinivasan**
Signed-off-by: André Srinivasan <andre@redislabs.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/.github/Contributing.md.

## What is the current behavior?

When an argument list contains a substring with _-r_ it is treated as the `-registry` flag. For example

```
service -configdir /foo/ba-r/
```

The _-r_ in _ba-r_ is seen as the `-registry` flag

## Issue Number:

Resolves #78 

## What is the new behavior?

Explicitly check for the regexp `^-(cp|configProvider)` and `^-(r|registry)`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Other information

Output `go test -v` before code changes

```
=== RUN   TestNewAllFlags
--- PASS: TestNewAllFlags (0.00s)
=== RUN   TestNewDefaultsNoFlags
--- PASS: TestNewDefaultsNoFlags (0.00s)
=== RUN   TestNewDefaultForCP
--- PASS: TestNewDefaultForCP (0.00s)
=== RUN   TestNewOverrideForCP
--- PASS: TestNewOverrideForCP (0.00s)
=== RUN   TestNewDefaultForConfigProvider
--- PASS: TestNewDefaultForConfigProvider (0.00s)
=== RUN   TestNewOverrideConfigProvider
--- PASS: TestNewOverrideConfigProvider (0.00s)
=== RUN   TestNewOverrideRegistry
--- PASS: TestNewOverrideRegistry (0.00s)
=== RUN   TestDashR
    flags_test.go:104:
            Error Trace:    flags_test.go:104
            Error:          Not equal:
                            expected: "/foo/ba-r/"
                            actual  : "-r=."

                            Diff:
                            --- Expected
                            +++ Actual
                            @@ -1 +1 @@
                            -/foo/ba-r/
                            +-r=.
            Test:           TestDashR
--- FAIL: TestDashR (0.00s)
=== RUN   TestConfDirEquals
--- PASS: TestConfDirEquals (0.00s)
FAIL
exit status 1
FAIL    github.com/edgexfoundry/go-mod-bootstrap/bootstrap/flags    0.004s
```

Output `go test -v` after code changes

```
=== RUN   TestNewAllFlags
--- PASS: TestNewAllFlags (0.00s)
=== RUN   TestNewDefaultsNoFlags
--- PASS: TestNewDefaultsNoFlags (0.00s)
=== RUN   TestNewDefaultForCP
--- PASS: TestNewDefaultForCP (0.00s)
=== RUN   TestNewOverrideForCP
--- PASS: TestNewOverrideForCP (0.00s)
=== RUN   TestNewDefaultForConfigProvider
--- PASS: TestNewDefaultForConfigProvider (0.00s)
=== RUN   TestNewOverrideConfigProvider
--- PASS: TestNewOverrideConfigProvider (0.00s)
=== RUN   TestNewOverrideRegistry
--- PASS: TestNewOverrideRegistry (0.00s)
=== RUN   TestDashR
--- PASS: TestDashR (0.00s)
=== RUN   TestConfDirEquals
--- PASS: TestConfDirEquals (0.00s)
PASS
ok  	github.com/edgexfoundry/go-mod-bootstrap/bootstrap/flags	0.004s
```

### CODE REVIEW

File: bootstrap/flags/flags_test.go [hunk 1]
```diff
@@ -96,3 +96,17 @@ func TestNewOverrideRegistry(t *testing.T) {
 
 	assert.Equal(t, expectedRegistryUrl, actual.RegistryUrl())
 }
+
+func TestDashR(t *testing.T) {
```
Comment (lenny-intel) [inline bootstrap/flags/flags_test.go:100]: Please add a test for our most common use which is `"-cp=consul.http://edgex-core-consul:8500", "--registry", "--confdir=/res"` to make sure the first conditional for -cp changed to regex is still handling this properly.

**Review by lenny-intel — CHANGES_REQUESTED** [review]
Code looks good, just need one additional unit test.

File: bootstrap/flags/flags_test.go (hunk 1 above)
Comment (lenny-intel) [reply bootstrap/flags/flags_test.go:100]: Note that the expected value for UseRegistry() is true and for RegistryUrl is constant `UseRegistryNoUrlValue = "."`

Comment (andresrinivasan) [reply bootstrap/flags/flags_test.go:100]: Good test. Corrected an issue. Just pushed.

**Review by lenny-intel — APPROVED** [review]
LGTM
