### PR TITLE
fix: Ensure exit with non-zero code when error occurs

### LINKED ISSUE #318: Device Service Exits With Success If Port Bind Fails
# 🐞 Bug Report

### Description

When the device service is unable to bind to the service port, it will exit with a successful exit code of `0`. This causes confusion as the services appears to be running just fine and then just decides to exit after being started. Having a proper exit code will help identify that there was an issue with starting the service.

#### Minimal Reproduction
Run more than one instance of a device service
```shell
DEVICE_DISCOVERY_ENABLED=false EDGEX_SECURITY_SECRET_STORE=false ./device-onvif-camera -c ./res --registry -cp=consul.http://localhost:8500; echo "Exit Code: $?"
```

## 🔥 Exception or Error
<pre><code>
level=INFO ts=2022-04-09T00:58:31.280514192Z app=device-onvif-camera source=config.go:373 msg="Loaded service configuration from ./res/configuration.toml"
level=INFO ts=2022-04-09T00:58:31.281102819Z app=device-onvif-camera source=variables.go:352 msg="Variables override of 'Device.Discovery.Enabled' by environment variable: DEVICE_DISCOVERY_ENABLED=false"
level=INFO ts=2022-04-09T00:58:31.281227473Z app=device-onvif-camera source=config.go:159 msg="Using Configuration Provider access token of length 0"
level=INFO ts=2022-04-09T00:58:31.281238478Z app=device-onvif-camera source=config.go:348 msg="Using Configuration provider (consul) from: http://localhost:8500 with base path of edgex/devices/2.0/device-onvif-camera"
level=INFO ts=2022-04-09T00:58:31.287947547Z app=device-onvif-camera source=variables.go:352 msg="Variables override of 'Device.Discovery.Enabled' by environment variable: DEVICE_DISCOVERY_ENABLED=false"
level=INFO ts=2022-04-09T00:58:31.288090295Z app=device-onvif-camera source=config.go:510 msg="Configuration has been pulled from Configuration provider (1 envVars overrides applied)"
level=INFO ts=2022-04-09T00:58:31.288124978Z app=device-onvif-camera source=registry.go:61 msg="Using Registry access token of length 0"
level=INFO ts=2022-04-09T00:58:31.288136835Z app=device-onvif-camera source=registry.go:85 msg="Using Registry (consul) from http://localhost:8500"
level=INFO ts=2022-04-09T00:58:31.369887232Z app=device-onvif-camera source=httpserver.go:123 msg="Web server starting (0.0.0.0:59984)"
level=INFO ts=2022-04-09T00:58:31.369935587Z app=device-onvif-camera source=messaging.go:69 msg="Setting options for secure MessageBus with AuthMode='usernamepassword' and SecretName='redisdb"
level=INFO ts=2022-04-09T00:58:31.370002533Z app=device-onvif-camera source=messaging.go:99 msg="Connected to redis Message Bus @ redis://localhost:6379 publishing on 'edgex/events/device' prefix topic with AuthMode='usernamepassword'"
level=INFO ts=2022-04-09T00:58:31.370036579Z app=device-onvif-camera source=init.go:154 msg="Check core-metadata service's status via Registry..."
level=ERROR ts=2022-04-09T00:58:31.370186615Z app=device-onvif-camera source=httpserver.go:135 msg="Web server failed: listen tcp 0.0.0.0:59984: bind: address already in use"
level=INFO ts=2022-04-09T00:58:31.370247077Z app=device-onvif-camera source=messaging.go:89 msg="Disconnected from MessageBus"
level=INFO ts=2022-04-09T00:58:31.370253317Z app=device-onvif-camera source=httpserver.go:118 msg="Web server shutting down"
level=INFO ts=2022-04-09T00:58:31.37027991Z app=device-onvif-camera source=httpserver.go:120 msg="Web server shut down"
level=INFO ts=2022-04-09T00:58:31.370280954Z app=device-onvif-camera source=config.go:449 msg="Watching for '/Writable' configuration changes has stopped"
level=INFO ts=2022-04-09T00:58:31.372599893Z app=device-onvif-camera source=init.go:56 msg="Service clients initialize successful."
level=INFO ts=2022-04-09T00:58:31.37262581Z app=device-onvif-camera source=restrouter.go:47 msg="Registering v2 routes..."
level=INFO ts=2022-04-09T00:58:31.378188884Z app=device-onvif-camera source=driver.go:86 msg="Initializing device client for '3fa1fe68-b915-4053-a3e1-1027f5ea88f4' camera"
level=ERROR ts=2022-04-09T00:58:34.430108582Z app=device-onvif-camera source=driver.go:90 msg="failed to initial device client for '3fa1fe68-b915-4053-a3e1-1027f5ea88f4' camera, skipping this device."
level=INFO ts=2022-04-09T00:58:34.430218035Z app=device-onvif-camera source=basenotificationresthandler.go:56 msg="Route /api/v2/onvifevent/{deviceName}/{resourceName} added."
level=INFO ts=2022-04-09T00:58:34.430228585Z app=device-onvif-camera source=driver.go:104 msg="Driver initialized."
level=INFO ts=2022-04-09T00:58:34.431112286Z app=device-onvif-camera source=service.go:216 msg="device service device-onvif-camera exists, updating it"
level=INFO ts=2022-04-09T00:58:34.43199397Z app=device-onvif-camera source=profiles.go:54 msg="Loading pre-defined profiles from /opt/intel/projects/device-onvif-camera/cmd/res/profiles"
level=INFO ts=2022-04-09T00:58:34.43501496Z app=device-onvif-camera source=profiles.go:88 msg="Profile onvif-camera exists, using the existing one"
level=INFO ts=2022-04-09T00:58:34.435049271Z app=device-onvif-camera source=devices.go:49 msg="Loading pre-defined devices from /opt/intel/projects/device-onvif-camera/cmd/res/devices"
level=INFO ts=2022-04-09T00:58:34.435056744Z app=device-onvif-camera source=autodiscovery.go:33 msg="AutoDiscovery stopped: disabled by configuration"
level=INFO ts=2022-04-09T00:58:34.435060765Z app=device-onvif-camera source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2022-04-09T00:58:34.435063708Z app=device-onvif-camera source=message.go:51 msg="Starting device-onvif-camera 0.0.0 "
level=INFO ts=2022-04-09T00:58:34.435066962Z app=device-onvif-camera source=message.go:55 msg="Camera device service started"
level=INFO ts=2022-04-09T00:58:34.435069728Z app=device-onvif-camera source=message.go:58 msg="Service started in: 3.155207639s"
level=INFO ts=2022-04-09T00:58:34.435072179Z app=device-onvif-camera source=bootstrap.go:135 msg="Un-Registering service from the Registry"
Exit Code: 0

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
edgex-compose  docker services, plus natively running device service binary

**EdgeX Version [**REQUIRED**]:**
Jakarta

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by lenny-intel**
fixes #318

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **Not unit testable**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **N/A**
  <link to docs PR>

## Testing Instructions
Use this branch in device SDK and Device Rest
Run Device Rest
Press control C
Verify  `echo $?` returns 0
Run Device Rest
Run Device Rest in another terminal
Verify if fails due to port bind error
Verify  `echo $?` returns 1

### CODE REVIEW

File: bootstrap/handlers/httpserver.go [hunk 1]
```diff
@@ -139,10 +140,15 @@ func (b *HttpServer) BootstrapHandler(
 
 		b.isRunning = true
 		err := server.ListenAndServe()
-		if err != nil {
+		// "Server closed" error occurs when Shutdown above is called in the Done processing, so it can be ignored
+		if err != nil && err.Error() != "http: Server closed" {
```
Comment (cloudxxx8) [inline bootstrap/handlers/httpserver.go:144]: comparing the error message is fragile
use 
`err != server.ErrServerClosed` instead
https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/net/http/server.go;l=2997

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

File: bootstrap/handlers/httpserver.go (hunk 1 above)
Comment (lenny-intel) [reply bootstrap/handlers/httpserver.go:144]: Great suggestion! THX!

Comment (lenny-intel) [reply bootstrap/handlers/httpserver.go]: Fixed

File: bootstrap/handlers/httpserver.go [hunk 2]
```diff
@@ -123,7 +125,6 @@ func (b *HttpServer) BootstrapHandler(
 		defer wg.Done()
 
 		<-ctx.Done()
-		lc.Info("Web server shutting down")
```
Comment (ajcasagrande) [inline bootstrap/handlers/httpserver.go:126]: why remove this?

File: bootstrap/handlers/httpserver.go [hunk 3]
```diff
@@ -139,10 +140,15 @@ func (b *HttpServer) BootstrapHandler(
...
-		if err != nil {
+		// "Server closed" error occurs when Shutdown above is called in the Done processing, so it can be ignored
+		if err != nil && err != http.ErrServerClosed {
+			// Other errors occur during bootstrapping, like port bind fails, are considered fatal
 			lc.Errorf("Web server failed: %v", err)
 			cancel := container.CancelFuncFrom(dic.Get)
-			cancel() // this will caused the service to stop
+			cancel() // this will clean up any long-running go functions that may have started
+			// Give time for clean up to occur before exiting.
+			time.Sleep(1 * time.Millisecond)
```
Comment (ajcasagrande) [inline bootstrap/handlers/httpserver.go:150]: why 1 millis sleep? Is this a trick/hack? Does `cancel()` return before completed?

File: bootstrap/bootstrap.go [hunk 4]
```diff
@@ -195,6 +195,11 @@ func Run(
 		handlers,
 	)
 
+	if !success {
+		cancel()
```
Comment (ajcasagrande) [inline bootstrap/bootstrap.go:199]: can we log something here?

**Review by cloudxxx8 — APPROVED** [review]
LGTM

File: bootstrap/handlers/httpserver.go (hunk 3 above)
Comment (lenny-intel) [reply bootstrap/handlers/httpserver.go:150]: Yes, a hack because `cancel()` write to the channel and returns before receivers have completed.
But this made me think and realized we have the wait group to use instead of sleep.

File: bootstrap/bootstrap.go (hunk 4 above)
Comment (lenny-intel) [reply bootstrap/bootstrap.go:201]: This only occurs when a bootstrap handler fails. The handler will have logged an error message. I add comment why we don't need to log.

File: bootstrap/handlers/httpserver.go (hunk 2 above)
Comment (lenny-intel) [reply bootstrap/handlers/httpserver.go:126]: Felt it was redundant with the `lc.Info("Web server shut down")` message 2 lines down.

File: bootstrap/handlers/httpserver.go [hunk 5]
```diff
@@ -144,10 +144,14 @@ func (b *HttpServer) BootstrapHandler(
...
+
+			// Allow any long-running go functions that may have started to stop before exiting
 			cancel := container.CancelFuncFrom(dic.Get)
-			cancel() // this will clean up any long-running go functions that may have started
-			// Give time for clean up to occur before exiting.
-			time.Sleep(1 * time.Millisecond)
+			cancel()
+
+			// Wait for all long-running go functions to stop before exiting.
+			wg.Done()
```
Comment (ajcasagrande) [inline bootstrap/handlers/httpserver.go:153]: This struck me as odd, as usually you don't see a call to `wg.Done` right before a `wg.Wait`. Expanding the code a bit, it looks like you are doing this because this go-routine's `defer` which calls `wg.Done` won't yet have been called, correct?

 Can you add a comment on why it is needed?

Comment (lenny-intel) [reply bootstrap/handlers/httpserver.go:153]: Yep, the wait will block if we don't do this since this is for the current go func. 
Yep will add a comment.

**Review by ajcasagrande — APPROVED** [review]
LGTM
