### PR TITLE
fix: Rework merge of configs to better handle empty values

### LINKED ISSUE #501: [WIP BUG] Empty value not handle properly when merging Common & Private config
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Config

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]

Settings with empty values are removed when pulled from Config Provider.
Need better way to remove unspecified empty values from configure p[prior to merging into main config.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by lenny-intel**
fixes #501

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
Build Core Data/ App Template/ Device Simple with this branch
Run each and verify the following
- Configs are loaded from file and pushed to Config Provider as expected
-   - Common configs and private configs merged without losing empty setting in private config
- Configs are loaded from Config Provider as expected
   - Common configs and private configs merged without losing empty setting in private config
- Writable changes are handled at all levels 
    - Private
    - All Common
    - App or Device common

### CODE REVIEW

File: bootstrap/config/config.go [hunk 1]
```diff
@@ -48,11 +48,10 @@ import (
 )
 
 const (
-	writableKey       = "/Writable"
+	writableKey       = "Writable"
```
Comment (ejlee3) [inline bootstrap/config/config.go:51]: are there any changes where we needed writableKey to have the `/` and it doesn't because of this change?

File: bootstrap/utils/utils.go [hunk 2]
```diff
@@ -68,45 +70,62 @@ func MergeMaps(dest map[string]any, src map[string]any) {
...
+		return nil, fmt.Errorf("could not create map from %T: %s", src, err.Error())
+	}
+
+	removeMapUnusedSettings(srcMap, baseKey, usedSettingKeys)
+
+	return srcMap, nil
+}
+
+// removeMapUnusedSettings iterates over a map and removes any settings not in list of valid keys
+func removeMapUnusedSettings(target map[string]any, baseKey string, validKeys map[string]any) {
```
Comment (ejlee3) [inline bootstrap/utils/utils.go:86]: does this name fit better?
```suggestion
func removeUnusedSettingsFromMap(target map[string]any, baseKey string, validKeys map[string]any) {
```

File: bootstrap/config/config.go [hunk 3]
```diff
@@ -577,36 +611,20 @@ func (cp *Processor) loadConfigYamlFromFile(yamlFile string) (map[string]any, er
...
-}
-
 // GetConfigFileLocation uses the environment variables and flags to determine the location of the configuration
 func GetConfigFileLocation(lc logger.LoggingClient, flags flags.Common) string {
 	configDir := environment.GetConfigDir(lc, flags.ConfigDirectory())
 	profileDir := environment.GetProfileDir(lc, flags.Profile())
 	configFileName := environment.GetConfigFileName(lc, flags.ConfigFileName())
 
-	return configDir + pathSep + profileDir + configFileName
+	return configDir + utils.PathSep + profileDir + configFileName
```
Comment (ejlee3) [inline bootstrap/config/config.go:620]: should this use a filepathpath.Join? that way it is os independent? also does profileDir already have a trailing PathSep?

File: bootstrap/config/config.go (hunk 1 above)
Comment (lenny-intel) [reply bootstrap/config/config.go:51]: Nope, looked at the code that this is passed to and it looks for the `/` and strips it off if it has it.

File: bootstrap/config/config.go (hunk 3 above)
Comment (lenny-intel) [reply bootstrap/config/config.go:620]: Nope, because this is a Consul path which is always Linux style.

Comment (lenny-intel) [reply bootstrap/config/config.go:620]: Yes, Good catch!

File: bootstrap/utils/utils.go (hunk 2 above)
Comment (lenny-intel) [reply bootstrap/utils/utils.go]: done

File: bootstrap/config/config.go (hunk 3 above)
Comment (lenny-intel) [reply bootstrap/config/config.go]: reworked

File: bootstrap/utils/utils_test.go [hunk 4]
```diff
@@ -123,32 +152,82 @@ func TestMergeConfigs(t *testing.T) {
...
 	assert.NotZero(t, serviceConfig.Writable.StoreAndForward.MaxRetryCount)
 	assert.NotEmpty(t, serviceConfig.Trigger.Type)
 }
 
-func TestRemoveZeroValues(t *testing.T) {
-	config := ConfigurationMockStruct{
-		Registry: config.RegistryInfo{
-			Host: "localhost",
-			Port: 8500,
+func TestRemoveUnusedSettings(t *testing.T) {
```
Comment (ejlee3) [inline bootstrap/utils/utils_test.go:160]: Is this supposed to be changed?

```suggestion
func TestRemoveUnusedSettingsFromMap(t *testing.T) {
```

Comment (lenny-intel) [reply bootstrap/utils/utils_test.go:160]: TestRemoveUnusedSettings is correct

**Review by ejlee3 — APPROVED** [review]
LGTM!

**Review by jim-wang-intel — APPROVED** [review]
